Loading conda_R/4.0.x
here() starts at /users/mkaras/_PROJECTS/upstrap_manuscript
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.0.6     ✔ dplyr   1.0.4
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘matrixStats’

The following object is masked from ‘package:dplyr’:

    count

Warning message:
In dir.create(path = res_fdir_agg) :
  '/users/mkaras/_PROJECTS/upstrap_manuscript/numerical_experiments/results_CL_shared/2021-02-15-twosample_ttest_agg' already exists
dir.exists(path = res_fdir_agg): TRUE
dir.exists(path = res_fdir_raw): TRUE
50
100
150
200
2.40127316600747
